In [102]:
# Importing the CSV Data from my desktop 
import csv
with open('C:/Users/Yenem/Desktop/movie_data.csv', 'r') as csvfile:
   spamreader = csv.reader(csvfile, delimiter= ',')
   for row in spamreader:
    print (','.join(row))


review,sentiment
In 1974, the teenager Martha Moxley (Maggie Grace) moves to the high-class area of Belle Haven, Greenwich, Connecticut. On the Mischief Night, eve of Halloween, she was murdered in the backyard of her house and her murder remained unsolved. Twenty-two years later, the writer Mark Fuhrman (Christopher Meloni), who is a former LA detective that has fallen in disgrace for perjury in O.J. Simpson trial and moved to Idaho, decides to investigate the case with his partner Stephen Weeks (Andrew Mitchell) with the purpose of writing a book. The locals squirm and do not welcome them, but with the support of the retired detective Steve Carroll (Robert Forster) that was in charge of the investigation in the 70's, they discover the criminal and a net of power and money to cover the murder.<br /><br />"Murder in Greenwich" is a good TV movie, with the true story of a murder of a fifteen years old girl that was committed by a wealthy teenager whose mother was a Kennedy. The powerful

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1346: character maps to <undefined>

In [103]:
# Reading the first 10 rows of the data
import pandas as pd

df = pd.read_csv('C:/Users/Yenem/Desktop/movie_data.csv')
df.head(10)


review  sentiment
0  In 1974, the teenager Martha Moxley (Maggie Gr...          1
1  OK... so... I really like Kris Kristofferson a...          0
2  ***SPOILER*** Do not read this, if you think a...          0
3  hi for all the people who have seen this wonde...          1
4  I recently bought the DVD, forgetting just how...          0
5  Leave it to Braik to put on a good show. Final...          1
6  Nathan Detroit (Frank Sinatra) is the manager ...          1
7  To understand "Crash Course" in the right cont...          1
8  I've been impressed with Chavez's stance again...          1
9  This movie is directed by Renny Harlin the fin...          1

In [104]:
#Building Bag-of-words model with scikit-learn
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df=1)
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [105]:
#tokenizing and counting the word occurrences with corpus of text documents

corpus = ['The sun is shining',
        'The weather is sweet',
        'The sun is shining, the weather is sweet, and one and one is two'
  
        ]
bag = vectorizer.fit_transform(corpus)
bag.shape, bag

((3, 9), <3x9 sparse matrix of type '<class 'numpy.int64'>'
 	with 17 stored elements in Compressed Sparse Row format>)

In [106]:

bag.toarray()

array([[0, 1, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 1],
       [2, 3, 2, 1, 1, 1, 2, 1, 1]], dtype=int64)

In [107]:
# feature vectors
vectorizer.vocabulary_

{'and': 0,
 'is': 1,
 'one': 2,
 'shining': 3,
 'sun': 4,
 'sweet': 5,
 'the': 6,
 'two': 7,
 'weather': 8}

In [108]:
vectorizer.vocabulary_.get('sweet')

5

In [109]:

vectorizer.transform(['Something completely new .']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [110]:

print(count.vocabulary_)

{'sun': 4, 'one': 2, 'and': 0, 'is': 1, 'sweet': 5, 'two': 7, 'the': 6, 'shining': 3, 'weather': 8}


In [111]:
#Tf-idf
np.set_printoptions(precision=2)

In [112]:
#TfidfTransformer() takes the raw term frequencies
#from CountVectorizer as input and transforms them into tf-idfs
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer(use_idf=True, norm='l2', smooth_idf=True)
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[ 0.    0.43  0.    0.56  0.56  0.    0.43  0.    0.  ]
 [ 0.    0.43  0.    0.    0.    0.56  0.43  0.    0.56]
 [ 0.5   0.45  0.5   0.19  0.19  0.19  0.3   0.25  0.19]]


In [113]:

tf_is = 3
n_docs = 3
idf_is = np.log((n_docs+1) / (3+1))
tfidf_is = tf_is * (idf_is + 1)
print('tf-idf of term "is" = %.2f' % tfidf_is)

tf-idf of term "is" = 3.00


In [114]:

tfidf = TfidfTransformer(use_idf=True, norm=None, smooth_idf=True)
raw_tfidf = tfidf.fit_transform(count.fit_transform(docs)).toarray()[-1]
raw_tfidf 

array([ 3.39,  3.  ,  3.39,  1.29,  1.29,  1.29,  2.  ,  1.69,  1.29])

In [115]:
# Feature extraction using tf-idf with a counts example


from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer(smooth_idf=False)
transformer 

TfidfTransformer(norm='l2', smooth_idf=False, sublinear_tf=False,
         use_idf=True)

In [116]:
l2_tfidf = raw_tfidf / np.sqrt(np.sum(raw_tfidf**2))
l2_tfidf

array([ 0.5 ,  0.45,  0.5 ,  0.19,  0.19,  0.19,  0.3 ,  0.25,  0.19])

In [84]:

df.shape

(50000, 2)

In [117]:
df.head(11)

review  sentiment
0   In 1974, the teenager Martha Moxley (Maggie Gr...          1
1   OK... so... I really like Kris Kristofferson a...          0
2   ***SPOILER*** Do not read this, if you think a...          0
3   hi for all the people who have seen this wonde...          1
4   I recently bought the DVD, forgetting just how...          0
5   Leave it to Braik to put on a good show. Final...          1
6   Nathan Detroit (Frank Sinatra) is the manager ...          1
7   To understand "Crash Course" in the right cont...          1
8   I've been impressed with Chavez's stance again...          1
9   This movie is directed by Renny Harlin the fin...          1
10  I once lived in the u.p and let me tell you wh...          0

In [118]:
df[:10]

review  sentiment
0  In 1974, the teenager Martha Moxley (Maggie Gr...          1
1  OK... so... I really like Kris Kristofferson a...          0
2  ***SPOILER*** Do not read this, if you think a...          0
3  hi for all the people who have seen this wonde...          1
4  I recently bought the DVD, forgetting just how...          0
5  Leave it to Braik to put on a good show. Final...          1
6  Nathan Detroit (Frank Sinatra) is the manager ...          1
7  To understand "Crash Course" in the right cont...          1
8  I've been impressed with Chavez's stance again...          1
9  This movie is directed by Renny Harlin the fin...          1

In [119]:
df

review  sentiment
0      In 1974, the teenager Martha Moxley (Maggie Gr...          1
1      OK... so... I really like Kris Kristofferson a...          0
2      ***SPOILER*** Do not read this, if you think a...          0
3      hi for all the people who have seen this wonde...          1
4      I recently bought the DVD, forgetting just how...          0
5      Leave it to Braik to put on a good show. Final...          1
6      Nathan Detroit (Frank Sinatra) is the manager ...          1
7      To understand "Crash Course" in the right cont...          1
8      I've been impressed with Chavez's stance again...          1
9      This movie is directed by Renny Harlin the fin...          1
10     I once lived in the u.p and let me tell you wh...          0
11     Hidden Frontier is notable for being the longe...          1
12     It's a while ago, that I have seen Sleuth (197...          0
13     What is it about the French? First, they (appa...          0
14     This very strange movie is unlike anything mad...          1
15     I saw this movie on the strength of the single...          0
16     There are some great philosophical questions. ...          0
17     I was cast as the Surfer Dude in the beach sce...          1
18     I had high hopes for this one until they chang...          0
19     Set in and near a poor working class town in t...          1
20     Opulent sets and sumptuous costumes well photo...          0
21     i saw the film and i got screwed, because the ...          0
22     I'm getting a little tired of people misusing ...          0
23     How offensive! Those who liked this movie have...          0
24     What else can you say about this movie,except ...          0
25     Certain aspects of Punishment Park are less th...          1
26     First of all, I'd like to tell you that I'm in...          0
27     You should not take what I am about to say lig...          1
28     I love the Jurassic Park movies, they are thre...          0
29     The first series of Lost kicked off with a ban...          1
...                                                  ...        ...
49970  Tom Fontana's unforgettable "Oz" is hands down...          1
49971  Last weekend I bought this 'zombie movie' from...          0
49972  I watched the first few moments on TCM a few y...          1
49973  I saw this movie for the first time in 1988 wh...          1
49974  Al Pacino? Kim Basinger? Tea Leoni? Ryan O'Nea...          0
49975  Stanwyck at her villainous best, Robinson her ...          1
49976  An allegation of aggravated sexual assault alo...          0
49977  i thought this movie was wonderfully plotted i...          1
49978  Just like most people, I couldn't wait to see ...          0
49979  Dark comedy? Gallows humor? How does one make ...          1
49980  ****Probably will contain spoilers****<br /><b...          0
49981  I must be that one guy in America that didn't ...          0
49982  THE PLOT: A trucker (Kristofferson) battles a ...          0
49983  The Ladies Man is laugh out loud funny, with a...          1
49984  Well, the artyfartyrati of Cannes may have lik...          0
49985  The director was probably still in his early l...          0
49986  You know when you're on the bus and someone de...          0
49987  Five minutes into this movie you realize that ...          0
49988  ...If you've been laughing too much for a long...          0
49989  I love dissing this movie. My peers always try...          0
49990  OK. I think the TV show is kind of cute and it...          0
49991  Big disappointment. CLASH BY NIGHT is much to ...          0
49992  Cassidy(Kacia Brady)puts a gun in her mouth bl...          0
49993  With rapid intercutting of scenes of insane pe...          1
49994  When "Girlfight" came out, the reviews praised...          1
49995  OK, lets start with the best. the building. al...          0
49996  The British 'heritage film' industry is out of...          0
49997  I don't even know where to begi

In [120]:
# the last 500 characters before cleaning
df.loc[0, 'review'][-500:]

'old girl that was committed by a wealthy teenager whose mother was a Kennedy. The powerful and rich family used their influence to cover the murder for more than twenty years. However, a snoopy detective and convicted perjurer in disgrace was able to disclose how the hideous crime was committed. The screenplay shows the investigation of Mark and the last days of Martha in parallel, but there is a lack of the emotion in the dramatization. My vote is seven.<br /><br />Title (Brazil): Not Available'

In [89]:
df.loc[1, 'review'][-400:]

" waste of good talent, scenery and celluloid! <br /><br />I rented this piece of garbage for a buck, and I want my money back! I want my 2 hours back I invested on this Grade F waste of my time! Don't watch this movie, or waste 1 minute of your valuable time while passing through a room where it's playing or even open up the case that is holding the DVD! Believe me, you'll thank me for the advice!"

In [90]:
#Cleaning data by removing punctuation as well as HTML and other characters.
import re
def preprocessor(text):
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    text = re.sub('[\W]+', ' ', text.lower()) +\
        ' '.join(emoticons).replace('-', '')
    return text

In [121]:
#The last 500 characters after cleaning 
preprocessor(df.loc[0, 'review'][-500:])

'old girl that was committed by a wealthy teenager whose mother was a kennedy the powerful and rich family used their influence to cover the murder for more than twenty years however a snoopy detective and convicted perjurer in disgrace was able to disclose how the hideous crime was committed the screenplay shows the investigation of mark and the last days of martha in parallel but there is a lack of the emotion in the dramatization my vote is seven title brazil not available'

In [122]:
preprocessor(df.loc[1, 'review'][-500:])

'that had a plot for goodness sake this had none zilcho nada zippo empty of reason a complete waste of good talent scenery and celluloid i rented this piece of garbage for a buck and i want my money back i want my 2 hours back i invested on this grade f waste of my time don t watch this movie or waste 1 minute of your valuable time while passing through a room where it s playing or even open up the case that is holding the dvd believe me you ll thank me for the advice '

In [93]:
preprocessor("</a>This :) is :( a test :-)!")

'this is a test :) :( :)'

In [94]:
df['review'] = df['review'].apply(preprocessor)

In [95]:
def tokenizer(text):
    return text.split()

tokenizer('runners like running and thus they run.')

['runners', 'like', 'running', 'and', 'thus', 'they', 'run.']

In [96]:
#poter stemming
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()

def tokenizer_porter(text):
    return [porter.stem(word) for word in text.split()]

tokenizer_porter('runners like running and thus they run.')


['runner', 'like', 'run', 'and', 'thu', 'they', 'run.']

In [99]:
# LancasterStemmer
from nltk.stem.lancaster import LancasterStemmer
lancaster = LancasterStemmer()

def tokenizer_lancaster(text):
    return [lancaster.stem(word) for word in text.split()]

tokenizer_lancaster('runners like running and thus they run.')

['run', 'lik', 'run', 'and', 'thu', 'they', 'run.']

In [100]:
# Stop words to remove frequently occuring words 

import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Yenem\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [101]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
[w for w in tokenizer_porter('runners like running and thus they run.')[:] if w not in stop]

['runner', 'like', 'run', 'thu', 'run.']